[build]
    command = "npm run build"
    functions = "functions/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

# https://docs.netlify.com/site-deploys/overview/#deploy-contexts
# Specific branch context:
# Deploys from this branch will take these settings
# and override their current ones.
[context.develop]
  REACT_APP_API_HOST = "https://bucks-care-staging.herokuapp.com/"
